"""
Task — a single, period-specific compliance task belonging to a client
(e.g. "GSTR-3B, Jul 2026" for a specific client). A Task may optionally
trace back to the ComplianceSchedule that generated it, but always belongs
directly to a Client so one-off tasks (not tied to any recurring rule) are
also supported.
"""
from __future__ import annotations

from datetime import date, datetime
from typing import TYPE_CHECKING

from sqlalchemy import Date, DateTime, ForeignKey, String, func
from sqlalchemy import Enum as SAEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base
from app.models.enums import TaskStatus

if TYPE_CHECKING:
    from app.models.checklist_item import ChecklistItem
    from app.models.client import Client
    from app.models.compliance_schedule import ComplianceSchedule


class Task(Base):
    """A concrete, period-specific compliance task for a client."""

    __tablename__ = "tasks"

    id: Mapped[int] = mapped_column(primary_key=True)

    client_id: Mapped[int] = mapped_column(
        ForeignKey("clients.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Nullable: a Task can exist without a recurring schedule (a one-off
    # task), but when generated by the recurrence engine this points back
    # to the originating rule.
    compliance_schedule_id: Mapped[int | None] = mapped_column(
        ForeignKey("compliance_schedules.id", ondelete="SET NULL"), nullable=True, index=True
    )

    # Denormalized on purpose: even one-off tasks (no schedule) need a type,
    # and it keeps querying/filtering by type simple. e.g. "GSTR-3B".
    task_type: Mapped[str] = mapped_column(String(100), nullable=False, index=True)

    # Human-readable period label, e.g. "Jul 2026", "Q1 FY26-27", "FY 2025-26".
    period: Mapped[str] = mapped_column(String(50), nullable=False)

    due_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)

    # Stored as a plain string — see Client.partner_in_charge rationale.
    assignee: Mapped[str | None] = mapped_column(String(255), nullable=True, index=True)

    status: Mapped[TaskStatus] = mapped_column(
        SAEnum(
            TaskStatus,
            name="task_status",
            native_enum=True,
            # Store the human-readable values ("Not Started", "In Progress", ...)
            # as the Postgres enum labels, not the Python member names
            # (NOT_STARTED, IN_PROGRESS, ...). Without this, SQLAlchemy
            # defaults to using .name for the DB labels, which would silently
            # diverge from the .value strings used everywhere else (API
            # responses, server_default, seed data).
            values_callable=lambda enum_cls: [member.value for member in enum_cls],
        ),
        nullable=False,
        default=TaskStatus.NOT_STARTED,
        server_default=TaskStatus.NOT_STARTED.value,
        index=True,
    )

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    client: Mapped["Client"] = relationship(back_populates="tasks")
    compliance_schedule: Mapped["ComplianceSchedule | None"] = relationship(back_populates="tasks")
    checklist_items: Mapped[list["ChecklistItem"]] = relationship(
        back_populates="task", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Task id={self.id} type={self.task_type!r} period={self.period!r} status={self.status}>"
